# Generated by Django 6.1.1 on 2026-10-06 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("slug", models.SlugField(unique=True)),
                (
                    "card_title",
                    models.CharField(
                        blank=True,
                        help_text="Title on the service card; falls back to name.",
                        max_length=80,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True, max_length=500)),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Shown as a card on the home and services pages.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ("order", "name"),
            },
        ),
        migrations.CreateModel(
            name="Stylist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("bio", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "specialties",
                    models.ManyToManyField(
                        blank=True, related_name="stylists", to="services.category"
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField()),
                ("description", models.TextField(blank=True)),
                ("duration_minutes", models.PositiveSmallIntegerField(default=60)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="INR", max_digits=8
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="services",
                        to="services.category",
                    ),
                ),
            ],
            options={
                "ordering": ("category__order", "order", "name"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("category", "slug"),
                        name="unique_service_slug_per_category",
                    )
                ],
            },
        ),
    ]
