# Generated by Django 6.1.1 on 2026-10-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(default="Belleza", max_length=60)),
                ("footer_brand", models.CharField(default="Belleza", max_length=60)),
                ("address", models.CharField(blank=True, max_length=200)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "copyright_start_year",
                    models.PositiveSmallIntegerField(default=2023),
                ),
                ("map_embed_url", models.URLField(blank=True, max_length=1000)),
                ("hero_title", models.CharField(blank=True, max_length=120)),
                ("hero_subtitle", models.CharField(blank=True, max_length=200)),
                ("intro_text", models.TextField(blank=True)),
                (
                    "about_text",
                    models.TextField(
                        blank=True, help_text="Separate paragraphs with a blank line."
                    ),
                ),
            ],
            options={
                "verbose_name": "site settings",
                "verbose_name_plural": "site settings",
            },
        ),
    ]
